// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UrlStorage is an autogenerated mock type for the UrlStorage type
type UrlStorage struct {
	mock.Mock
}

// StoreUrl provides a mock function with given fields: ctx, code, url, expire
func (_m *UrlStorage) StoreUrl(ctx context.Context, code string, url string, expire time.Duration) error {
	ret := _m.Called(ctx, code, url, expire)

	if len(ret) == 0 {
		panic("no return value specified for StoreUrl")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, code, url, expire)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlStorage creates a new instance of UrlStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlStorage {
	mock := &UrlStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
