// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ShortenUrlService is an autogenerated mock type for the ShortenUrlService type
type ShortenUrlService struct {
	mock.Mock
}

// CreateShortenUrl provides a mock function with given fields: ctx, url, expire
func (_m *ShortenUrlService) CreateShortenUrl(ctx context.Context, url string, expire time.Duration) (string, error) {
	ret := _m.Called(ctx, url, expire)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortenUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, url, expire)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, url, expire)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, url, expire)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUrlByCode provides a mock function with given fields: ctx, code
func (_m *ShortenUrlService) GetUrlByCode(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetUrlByCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenUrlService creates a new instance of ShortenUrlService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenUrlService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenUrlService {
	mock := &ShortenUrlService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
