name: ci-pipeline

on:
  pull_request:
    branches: ["main"]

  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.0

      - name: Run test
        run: make docker-test

      - name: Login to Docker
        if: ${{ github.event_name != 'pull_request' }}
        run: make docker-login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: ${{ github.event_name != 'pull_request' }}
        run: make docker-release
